name: Deploy Vue Website to Hostinger

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: iamfelixk.de
        username: u431686214
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/
        server-dir: public_html/
        port: 21
